language: go

go:
  - "1.11"

script:
  - go test -v -race -cover -covermode=atomic github.com/z0rr0/gopwgen/pwgen

branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
